name: Validate

on:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:

  codeChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Check Spotless
        run: ./gradlew spotlessCheck
      - name: Run Unit Tests
        run: ./gradlew test

  buildPlugin:
    runs-on: ubuntu-latest
    needs: codeChecks
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Build plugin
        run: ./gradlew --no-configuration-cache buildPlugin
      - uses: actions/upload-artifact@v4.3.3
        id: artifact
        with:
          name: distributions
          path: build/distributions
      - uses: mshick/add-pr-comment@v2
        with:
          message-id: download-artifact-comment
          refresh-message-position: true
          message: |
            Artifact build on last commit: [distributions.zip](${{ steps.artifact.outputs.artifact-url }}). 
            For MacOS users: there is a zip inside this zip and Finder unzips them both at once. Use `unzip distributions.zip` from Terminal or [check solution for Archive Manager](https://apple.stackexchange.com/questions/443607/is-there-a-way-to-prevent-macoss-archive-utility-from-unarchiving-inner-zip-fil).

  runPluginVerifier:
    runs-on: ubuntu-latest
    needs: codeChecks
    strategy:
      matrix:
        version: [ "2023.3", "2024.3" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Verify plugin
        run: ./gradlew --no-configuration-cache -PverifyVersion=${{ matrix.version }} verifyPlugin
      - name: Get result directories
        run: |
          DIRECTORIES=$(ls build/reports/pluginVerifier/ | jq -R -s -c 'split("\n")[:-1]')
          echo "DIRECTORIES=$DIRECTORIES" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: pluginVerifierReports
          path: build/reports/pluginVerifier
    outputs:
      directories: ${{ env.DIRECTORIES }}

  addComments:
    runs-on: ubuntu-latest
    needs: runPluginVerifier
    strategy:
      matrix:
        dir: ${{fromJson(needs.runPluginVerifier.outputs.directories)}}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pluginVerifierReports
      - name: Publish report
        uses: mshick/add-pr-comment@v2
        with:
          message-id: verify-plugin-comment-${{ matrix.dir }}
          refresh-message-position: true
          message-path: |
            ${{ matrix.dir }}/report.md
